---
- name: Install Dependencies on Debian
  hosts: localhost
  tasks:
    - name: Update APT package
      become: yes
      apt:
        update_cache: yes

    - name: Install curl, neofetch, nvim
      become: yes
      apt:
        name: 
          - curl
          - neofetch
          - neovim
        state: present

    - name: Install n package manager
      become: yes
      shell: |
        curl -L https://git.io/n-install | N_PREFIX=/usr/local bash -s -- -y     
